### ISSUE TITLE
which is better between pmsignature and SomaticSignatures ??

### ISSUE THREAD

**Issue by WinterLi1993** [julian-gehring/SomaticSignatures#1]
Hi, author, 
        which way I should use , pmsignature  or  SomaticSignatures  ??
        Expecting your answer! 
Best wishes!

**Comment by juliangehring** [comment]
Which of the two approaches may be more suited for your analysis depends largely on the scientific question you are trying to address as well as the your data. As both software packages are also based on different methodological approaches, asking for the generally "better" seems not useful. I would suggest to read the manuscripts and have a look at the software documentation to understand the differences of both methods. This way, you will be able to decide what will be the more suited analysis approach for your research.
