### ISSUE TITLE
How to compute matrix H for known signatures?

### ISSUE THREAD

**Issue by svkazakov** [julian-gehring/SomaticSignatures#3]
Hi, 

Thanks for a great package!

As I read in many articles, there are several databases with already identified mutational signatures (for example, COSMIC database, http://cancer.sanger.ac.uk/cosmic/signatures). 
And how can I compute a matrix H (contribution of each signature to the alterations present in each sample) with already specified matrices M (motif matrix) and W (signatures matrix)?

<br/><br/><br/>

And I think it would be a good improvement to add such method to the package SomaticSignatures.
<br/>

Thanks for an advice,
Sergey Kazakov, ITMO University.

**Comment by juliangehring** [comment]
I would consider the comparison with a set of known signatures an open research question. A suitable comparison method will very much depend on the decomposition method, i.e. the way the signatures were estimated in the first place. Some examples have been discussed before:
https://support.bioconductor.org/p/88884/
https://support.bioconductor.org/p/61913/

**Comment by juliangehring** [comment]
I agree that having such a method would be useful to have, but due to the reasons described above, I think that having a generally applicable solution would be a challenging topic with respect to the focus of the `SomaticSignatures` package.

**Comment by juliangehring** [comment]
Please feel free to reopen this issue if needed.
