### ISSUE TITLE
Making initial object for SomaticSignatures

### ISSUE THREAD

**Issue by beginner984** [julian-gehring/SomaticSignatures#8]
Hi,

This is not a problem with this software rather my confusion

I have a list of .vcf files from WGS contains called SNV and indels. I have extracted information from them like below

```
> head(mutations)
  sampleID chr     pos ref mut
1    t_005   1  928006   G   A
2    t_005   1 1649842   G   T
3    t_005   1 2020408   G   A
4    t_005   1 2031677   T   A
5    t_005   1 2901878   G   A
6    t_005   1 3039338   G   A
> 

```

I want to make VRanges object from my vcf files or the information I extracted from .vcf files, because I need to find signature in my WGS samples, could you please help me?

Thanks a lot in advance

**Comment by juliangehring** [comment]
You can have a look at the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/SomaticSignatures/inst/doc/SomaticSignatures-vignette.html#orgheadline4) of the package that describes this step using the `VRanges` function of the `VariantAnnotation` package.
