### ISSUE TITLE
Simple usage instruction

### ISSUE THREAD

**Issue by nurmians** [julian-gehring/SomaticSignatures#9]
Would it be too much trouble to add some info here on github what I should expect your algorithm to do?

What does it use as input? I would like to just feed it VCF files.
What do I get as output?

**Comment by juliangehring** [comment]
You can find a detailed documentation, together with real-world examples, on the official package page in the Bioconductor repository: https://bioconductor.org/packages/SomaticSignatures/. 

I have added the link to the readme page.
